default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.py-tpl$
      - id: end-of-file-fixer
        exclude: \.(py-tpl|svg|ico)$
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        pass_filenames: false
        additional_dependencies:
          - pydantic>=2.7
          - pydantic-settings>=2.3
          - sqlalchemy[asyncio]>=2.0.30
          - fastapi>=0.115
          - types-PyYAML
